spring.application.name=artifName

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tickets
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# "update" le dice a Spring que cree o actualice las tablas automáticamente según nuestro código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Clave secreta de 256 bits para firmar los JWT
jwt.secret=9a4f2c8d3e1b7f6a5c4d3b2a1e0f9c8b7a6f5e4d3c2b1a0e9f8d7c6b5a4f3e2d